=== MarcosJimBos/barAssistantBack/src/xml/notes.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="notes">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="note" maxOccurs="unbounded" minOccurs="1">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="to" type="xs:string"/>
                            <xs:element name="from" type="xs:string"/>
                            <xs:element name="heading" type="xs:string"/>
                            <xs:element name="body">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="xs:string">
                                            <xs:attribute name="length" type="xs:int" use="optional"/>
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== MarcosJimBos/barAssistantBack/src/xml/notes.xml
<?xml version="1.0"?>
<notes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="notes.xsd">
    <note>
        <to>Tove</to>
        <from>Jani</from>
        <heading>Reminder</heading>
        <body length="100">Don't forget me this weekend!</body>
    </note>
    <note>
        <to>Pepe</to>
        <from>Ana</from>
        <heading>Salutacio</heading>
        <body length="100">Hola</body>
    </note>
</notes>
